export const SETTINGS_INDEX = [
  { kind: "page", page: "general",     label: "General",     desc: "Appearance, startup behaviour and general preferences.", kw: "settings preferences" },
  { kind: "page", page: "hub",         label: "Hub",         desc: "Project Hub, contribution heatmap and app-data management.", kw: "settings" },
  { kind: "page", page: "editor",      label: "Editor",      desc: "Font, wrapping and editing behaviour.", kw: "settings" },
  { kind: "page", page: "terminal",    label: "Terminal",    desc: "Font, cursor, scrollback and shell preferences.", kw: "settings" },
  { kind: "page", page: "git",         label: "Git",         desc: "Commit, fetch and gutter preferences.", kw: "settings" },
  { kind: "page", page: "canvas",      label: "Canvas",      desc: "Drawing surface and preview preferences.", kw: "settings" },
  { kind: "page", page: "keybindings", label: "Keybindings", desc: "Keyboard shortcuts.", kw: "settings shortcuts hotkeys" },
  { kind: "page", page: "extensions",  label: "Extensions",  desc: "Manage installed extensions.", kw: "settings chrome crx browser" },

  { kind: "row", page: "general", label: "Theme", desc: "Color theme for the workbench. Restart may be required for some elements.", kw: "appearance color dark light dark+" },
  { kind: "row", page: "general", label: "Zoom Level", desc: "Adjust the overall UI scale. 100% is the default.", kw: "zoom ui scale interface size magnify" },
  { kind: "row", page: "general", label: "Restore Previous Session", desc: "Reopen editors and layout from the last session when the app starts.", kw: "startup session tabs reopen layout" },
  { kind: "row", page: "general", label: "Show Hidden Files", desc: "Show dotfiles and hidden folders in the Project explorer.", kw: "explorer dotfiles hidden folders visibility" },
  { kind: "row", page: "general", label: "Auto Open Media Viewer", desc: "Automatically open images, videos, PDFs and audio in the Media Viewer when clicked in the Project explorer.", kw: "images videos pdf audio viewer preview" },
  { kind: "row", page: "general", label: "Confirm Before Delete", desc: "Show a confirmation dialog when deleting files or folders.", kw: "delete confirmation safety dialog" },
  { kind: "row", page: "general", label: "Telemetry", desc: "Anonymous usage stats that power the public download page. Off = nothing is sent.", kw: "analytics privacy usage stats data" },

  { kind: "row", page: "hub", label: "GitHub Username", desc: "For the contribution heatmap in Hub. Also asked during onboarding.", kw: "github profile heatmap account" },
  { kind: "row", page: "hub", label: "Contribution Heatmap", desc: "Show the GitHub contribution graph in the Project Hub.", kw: "github graph activity" },
  { kind: "row", page: "hub", label: "Custom Cursor", desc: "Smart custom cursor in Hub. Turn off for the normal OS cursor.", kw: "cursor pointer mouse" },
  { kind: "row", page: "hub", label: "Click Sounds", desc: "Soft click sound on Hub buttons. Turn off to stay silent.", kw: "sound audio feedback mute" },
  { kind: "row", page: "hub", label: "Wallpaper Opacity", desc: "How solid Hub panels stay when a wallpaper is set.", kw: "background transparency panel" },
  { kind: "row", page: "hub", label: "Reset Onboarding", desc: "Show the welcome page again (forgets the username).", kw: "welcome getting started tour" },
  { kind: "row", page: "hub", label: "Recent Projects", desc: "Clear the Hub's recent projects list.", kw: "clear recents history" },
  { kind: "row", page: "hub", label: "Main Storage Folder", desc: "App data for all projects (userData/projects): open or clear it.", kw: "storage app data clear folder userData" },

  { kind: "row", page: "editor", label: "Line Numbers", desc: "Show line numbers in the gutter.", kw: "gutter numbers" },
  { kind: "row", page: "editor", label: "Word Wrap", desc: "Wrap long lines (no horizontal scroll).", kw: "wrap lines scroll" },
  { kind: "row", page: "editor", label: "Autocompletion", desc: "Suggest popup (Ctrl+Space).", kw: "autocomplete suggestions intellisense popup" },
  { kind: "row", page: "editor", label: "Tab Accepts Suggestion", desc: "Tab accepts an open suggestion, otherwise normal indent.", kw: "tab complete suggestion indent" },
  { kind: "row", page: "editor", label: "Theme", desc: "vscodeDark / vscodeLight / oneDark. Applies instantly.", kw: "editor color theme dark light onedark" },
  { kind: "row", page: "editor", label: "Font Family", desc: "Editor font. Falls back to monospace if the font is missing.", kw: "font typeface monospace consolas fira jetbrains" },
  { kind: "row", page: "editor", label: "Font Size", desc: "Editor font size in pixels. Range 8-32.", kw: "font pixels text size" },
  { kind: "row", page: "editor", label: "Tab Size", desc: "Tab stop width (1-8).", kw: "indent width spaces" },
  { kind: "row", page: "editor", label: "Indent Unit", desc: "What to insert for a new indent.", kw: "indent spaces tab" },
  { kind: "row", page: "editor", label: "Auto Save", desc: "Auto-saves after a short pause. If it is off, press Ctrl+S.", kw: "save automatically" },
  { kind: "row", page: "editor", label: "Snippets", desc: "Code snippets in autocomplete (for, if, class, etc.).", kw: "templates autocomplete" },
  { kind: "row", page: "editor", label: "Vim Mode", desc: "Enable Vim keybindings (Esc, h/j/k/l, etc.).", kw: "vim keys modal editing" },

  { kind: "row", page: "terminal", label: "Font Family", desc: "Monospace font used in the integrated terminal.", kw: "terminal font typeface" },
  { kind: "row", page: "terminal", label: "Font Size", desc: "Terminal font size in pixels. Range 8-32.", kw: "terminal font pixels text size" },
  { kind: "row", page: "terminal", label: "Cursor Style", desc: "Shape of the terminal cursor.", kw: "block underline bar caret" },
  { kind: "row", page: "terminal", label: "Cursor Blink", desc: "Whether the cursor blinks.", kw: "caret blink" },
  { kind: "row", page: "terminal", label: "Scrollback", desc: "Number of lines to keep in the terminal buffer.", kw: "buffer history lines memory" },
  { kind: "row", page: "terminal", label: "Copy on Select", desc: "Automatically copy selected text to the clipboard.", kw: "clipboard selection copy" },

  { kind: "row", page: "git", label: "Auto Fetch", desc: "Automatically fetch from remotes in the background every few minutes.", kw: "remote pull sync background" },
  { kind: "row", page: "git", label: "Show Git Gutter", desc: "Show added/modified/deleted indicators in the editor gutter.", kw: "diff indicators editor marks" },
  { kind: "row", page: "git", label: "Confirm Before Commit", desc: "Require confirmation when committing without a message or with no staged changes.", kw: "commit safety dialog" },
  { kind: "row", page: "git", label: "Auto Stash on Pull", desc: "Automatically stash and reapply local changes when pulling.", kw: "stash pull rebase sync" },
  { kind: "row", page: "git", label: "Inline Blame", desc: "Show the last commit author and message inline at the end of the current line.", kw: "blame author commit line" },
  { kind: "row", page: "git", label: "About Git Integration", desc: "Idiot Box uses your system Git installation (git on PATH).", kw: "system git path info" },

  { kind: "row", page: "canvas", label: "Canvas Theme", desc: "Drawing canvas appearance. Auto follows the app theme (light/dark).", kw: "excalidraw color dark light" },
  { kind: "row", page: "canvas", label: "Autosave", desc: "Automatically save the drawing after each change.", kw: "drawing save excalidraw" },
  { kind: "row", page: "canvas", label: "Background", desc: "Drawing canvas background: solid black, solid white, or grid.", kw: "grid black white stage" },
  { kind: "row", page: "canvas", label: "Storage", desc: "The scratch drawing saves per-project (drawing.excalidraw).", kw: "file project save location" },
];
